# Generated by Django 4.0.5 on 2022-10-23 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coustumerfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coustumerfeedback',
            old_name='username',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='coustumerfeedback',
            name='mobile',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
